Vagrant.configure("2") do |config|
  config.vm.define "avarnierS" do |avarnierS|
    avarnierS.vm.hostname = "avarnierS"
    avarnierS.vm.box = "hashicorp/bionic64"
    avarnierS.vm.network "private_network", ip: "192.168.56.110"
    avarnierS.vm.synced_folder "./data", "/data"

    avarnierS.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
      vb.cpus = 1
    end

    avarnierS.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt upgrade -y
      curl -sfL https://get.k3s.io | sh -
      cp /var/lib/rancher/k3s/server/token /data/
    SHELL
  end

  config.vm.define "avarnierSW" do |avarnierSW|
    avarnierSW.vm.hostname = "avarnierSW"
    avarnierSW.vm.box = "hashicorp/bionic64"
    avarnierSW.vm.network "private_network", ip: "192.168.56.111"
    avarnierSW.vm.synced_folder "./data", "/data"

    avarnierSW.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
      vb.cpus = 1
    end

    avarnierSW.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt upgrade -y
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /data/token) sh -
    SHELL
  end
end