Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.hostname = "avarnierS"
  config.vm.synced_folder "./data", "/data"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
      cp /var/lib/rancher/k3s/server/token /data/
    SHELL
end